apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: opentranscribe-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: Beehive-Advisors/opentranscribe
      labels:
      - self-hosted
      - opentranscribe-runner
      dockerEnabled: true
      dockerdWithinRunnerContainer: true
      image: summerwind/actions-runner-dind:latest
      dockerdContainerResources:
        limits:
          cpu: "4"
          memory: "2Gi"
        requests:
          cpu: "1"
          memory: "1Gi"
